In [ ]:
!pip install PyPDF2
!pip install pandas
!pip install tabula-py

In [1]:
import PyPDF2 as file_pdf
import pandas as pd
from tabula.io import read_pdf

# Tarea 2

In [ ]:
"""Analice y trabaje con df2.
Unir los datos resultantes a partir de “df1 y df2” en una sola tabla y exportarlos a Excel. 
El cambio de librerias es aceptable, mientras cumpla el objetivo de la practica. 
Deberá especificar que librerías a utilizado de ser el caso."""

In [2]:
documento1 = read_pdf(input_path='EjemploPdf.pdf', pages='2', encoding='windows-1252')
documento1

[                State Mar-19 Mar-20 Growth 2018-19 2019-20 Growth.1
 0   Jammu and Kashmir    388    276   -29%   3,792   4,010       6%
 1    Himachal Pradesh    660    596   -10%   7,593   7,960       5%
 2              Punjab  1,166  1,181     1%  13,979  15,235       9%
 3          Chandigarh    162    153    -5%   1,779   1,988      12%
 4         Uttarakhand  1,451  1,195   -18%  15,150  14,722      -3%
 5             Haryana  4,561  4,874     7%  55,233  59,560       8%
 6               Delhi  3,722  3,273   -12%  39,845  44,161      11%
 7           Rajasthan  3,132  2,820   -10%  30,722  32,821       7%
 8       Uttar Pradesh  5,548  5,294    -5%  61,337  65,281       6%
 9               Bihar  1,177  1,056   -10%  10,755  12,640      18%
 10             Sikkim    160    189    19%   1,917   2,248      17%
 11  Arunachal Pradesh     85     67   -22%     398     581      46%
 12           Nagaland     46     39   -16%     227     317      40%
 13            Manipur     46     36   -22%     309     435      41%
 14            Mizoram     50     33   -33%     213     296      39%
 15            Tripura     64     67     5%     556     680      22%
 16          Meghalaya    127    133     5%   1,368   1,522      11%
 17              Assam    956    932    -3%   8,989  10,423      16%
 18        West Bengal  3,841  3,582    -7%  39,780  43,386       9%
 19          Jharkhand  2,149  2,049    -5%  23,916  22,847      -4%
 20             Odisha  2,626  2,633     0%  26,952  29,677      10%]

In [3]:
documento2 = read_pdf(input_path='EjemploPdf.pdf', pages='3', encoding = 'windows-1252', pandas_options = {'header': None})
documento2

[                         0       1       2     3         4         5     6
 0             Chhattisgarh   2,143   2,093   -2%    22,932    24,160    5%
 1           Madhya Pradesh   2,624   2,407   -8%    25,683    28,354   10%
 2                  Gujarat   6,521   6,820    5%    73,440    78,923    7%
 3            Daman and Diu     103      95   -8%     1,105     1,155    5%
 4   Dadra and Nagar Haveli     174     169   -3%     1,718     1,810    5%
 5              Maharashtra  15,596  15,002   -4%  1,70,289  1,85,917    9%
 6                Karnataka   6,983   7,144    2%    78,763    83,408    6%
 7                      Goa     389     316  -19%     4,103     4,280    4%
 8              Lakshadweep       1       1   54%        20        20    2%
 9                   Kerala   1,635   1,475  -10%    16,343    19,234   18%
 10              Tamil Nadu   6,941   6,178  -11%    70,562    74,430    5%
 11              Puducherry     184     149  -19%     1,924     1,871   -3%
 12                 Andaman     NaN     NaN   NaN       NaN       NaN   NaN
 13                     NaN      28      39   40%       297       361   21%
 14         &NicobarIslands     NaN     NaN   NaN       NaN       NaN   NaN
 15               Telangana   3,897   3,563   -9%    36,408    39,820    9%
 16          Andhra Pradesh   2,589   2,548   -2%    25,331    27,108    7%
 17         Other Territory     167     133  -21%     2,484     1,753  -29%
 18     Center Jurisdiction      74      81   10%       580     1,003   73%
 19                   Total  82,165  78,700   -4%  8,76,794  9,44,414    8%]

In [4]:
df1 = pd.DataFrame(documento1[0])
df2 = pd.DataFrame(documento2[0])
df2

                         0       1       2     3         4         5     6
0             Chhattisgarh   2,143   2,093   -2%    22,932    24,160    5%
1           Madhya Pradesh   2,624   2,407   -8%    25,683    28,354   10%
2                  Gujarat   6,521   6,820    5%    73,440    78,923    7%
3            Daman and Diu     103      95   -8%     1,105     1,155    5%
4   Dadra and Nagar Haveli     174     169   -3%     1,718     1,810    5%
5              Maharashtra  15,596  15,002   -4%  1,70,289  1,85,917    9%
6                Karnataka   6,983   7,144    2%    78,763    83,408    6%
7                      Goa     389     316  -19%     4,103     4,280    4%
8              Lakshadweep       1       1   54%        20        20    2%
9                   Kerala   1,635   1,475  -10%    16,343    19,234   18%
10              Tamil Nadu   6,941   6,178  -11%    70,562    74,430    5%
11              Puducherry     184     149  -19%     1,924     1,871   -3%
12                 Andaman     NaN     NaN   NaN       NaN       NaN   NaN
13                     NaN      28      39   40%       297       361   21%
14         &NicobarIslands     NaN     NaN   NaN       NaN       NaN   NaN
15               Telangana   3,897   3,563   -9%    36,408    39,820    9%
16          Andhra Pradesh   2,589   2,548   -2%    25,331    27,108    7%
17         Other Territory     167     133  -21%     2,484     1,753  -29%
18     Center Jurisdiction      74      81   10%       580     1,003   73%
19                   Total  82,165  78,700   -4%  8,76,794  9,44,414    8%

In [5]:
df2.columns = ['State', 'Mar-19', 'Mar-20', 'Growth', '2018-19', '2019-20', 'Growth.1']
df2

                     State  Mar-19  Mar-20 Growth   2018-19   2019-20 Growth.1
0             Chhattisgarh   2,143   2,093    -2%    22,932    24,160       5%
1           Madhya Pradesh   2,624   2,407    -8%    25,683    28,354      10%
2                  Gujarat   6,521   6,820     5%    73,440    78,923       7%
3            Daman and Diu     103      95    -8%     1,105     1,155       5%
4   Dadra and Nagar Haveli     174     169    -3%     1,718     1,810       5%
5              Maharashtra  15,596  15,002    -4%  1,70,289  1,85,917       9%
6                Karnataka   6,983   7,144     2%    78,763    83,408       6%
7                      Goa     389     316   -19%     4,103     4,280       4%
8              Lakshadweep       1       1    54%        20        20       2%
9                   Kerala   1,635   1,475   -10%    16,343    19,234      18%
10              Tamil Nadu   6,941   6,178   -11%    70,562    74,430       5%
11              Puducherry     184     149   -19%     1,924     1,871      -3%
12                 Andaman     NaN     NaN    NaN       NaN       NaN      NaN
13                     NaN      28      39    40%       297       361      21%
14         &NicobarIslands     NaN     NaN    NaN       NaN       NaN      NaN
15               Telangana   3,897   3,563    -9%    36,408    39,820       9%
16          Andhra Pradesh   2,589   2,548    -2%    25,331    27,108       7%
17         Other Territory     167     133   -21%     2,484     1,753     -29%
18     Center Jurisdiction      74      81    10%       580     1,003      73%
19                   Total  82,165  78,700    -4%  8,76,794  9,44,414       8%

In [6]:
unir = pd.concat([df1, df2], axis = 0, ignore_index = True)
unir

                     State  Mar-19  Mar-20 Growth   2018-19   2019-20 Growth.1
0        Jammu and Kashmir     388     276   -29%     3,792     4,010       6%
1         Himachal Pradesh     660     596   -10%     7,593     7,960       5%
2                   Punjab   1,166   1,181     1%    13,979    15,235       9%
3               Chandigarh     162     153    -5%     1,779     1,988      12%
4              Uttarakhand   1,451   1,195   -18%    15,150    14,722      -3%
5                  Haryana   4,561   4,874     7%    55,233    59,560       8%
6                    Delhi   3,722   3,273   -12%    39,845    44,161      11%
7                Rajasthan   3,132   2,820   -10%    30,722    32,821       7%
8            Uttar Pradesh   5,548   5,294    -5%    61,337    65,281       6%
9                    Bihar   1,177   1,056   -10%    10,755    12,640      18%
10                  Sikkim     160     189    19%     1,917     2,248      17%
11       Arunachal Pradesh      85      67   -22%       398       581      46%
12                Nagaland      46      39   -16%       227       317      40%
13                 Manipur      46      36   -22%       309       435      41%
14                 Mizoram      50      33   -33%       213       296      39%
15                 Tripura      64      67     5%       556       680      22%
16               Meghalaya     127     133     5%     1,368     1,522      11%
17                   Assam     956     932    -3%     8,989    10,423      16%
18             West Bengal   3,841   3,582    -7%    39,780    43,386       9%
19               Jharkhand   2,149   2,049    -5%    23,916    22,847      -4%
20                  Odisha   2,626   2,633     0%    26,952    29,677      10%
21            Chhattisgarh   2,143   2,093    -2%    22,932    24,160       5%
22          Madhya Pradesh   2,624   2,407    -8%    25,683    28,354      10%
23                 Gujarat   6,521   6,820     5%    73,440    78,923       7%
24           Daman and Diu     103      95    -8%     1,105     1,155       5%
25  Dadra and Nagar Haveli     174     169    -3%     1,718     1,810       5%
26             Maharashtra  15,596  15,002    -4%  1,70,289  1,85,917       9%
27               Karnataka   6,983   7,144     2%    78,763    83,408       6%
28                     Goa     389     316   -19%     4,103     4,280       4%
29             Lakshadweep       1       1    54%        20        20       2%
30                  Kerala   1,635   1,475   -10%    16,343    19,234      18%
31              Tamil Nadu   6,941   6,178   -11%    70,562    74,430       5%
32              Puducherry     184     149   -19%     1,924     1,871      -3%
33                 Andaman     NaN     NaN    NaN       NaN       NaN      NaN
34                     NaN      28      39    40%       297       361      21%
35         &NicobarIslands     NaN     NaN    NaN       NaN       NaN      NaN
36               Telangana   3,897   3,563    -9%    36,408    39,820       9%
37          Andhra Pradesh   2,589   2,548    -2%    25,331    27,108       7%
38         Other Territory     167     133   -21%     2,484     1,753     -29%
39     Center Jurisdiction      74      81    10%       580     1,003      73%
40                   Total  82,165  78,700    -4%  8,76,794  9,44,414       8%

In [12]:
unir.to_excel('tabla.xlsx',index = False)

In [13]:
leer = pd.read_excel('tabla.xlsx')
leer

                     State  Mar-19  Mar-20 Growth   2018-19   2019-20 Growth.1
0        Jammu and Kashmir     388     276   -29%     3,792     4,010       6%
1         Himachal Pradesh     660     596   -10%     7,593     7,960       5%
2                   Punjab   1,166   1,181     1%    13,979    15,235       9%
3               Chandigarh     162     153    -5%     1,779     1,988      12%
4              Uttarakhand   1,451   1,195   -18%    15,150    14,722      -3%
5                  Haryana   4,561   4,874     7%    55,233    59,560       8%
6                    Delhi   3,722   3,273   -12%    39,845    44,161      11%
7                Rajasthan   3,132   2,820   -10%    30,722    32,821       7%
8            Uttar Pradesh   5,548   5,294    -5%    61,337    65,281       6%
9                    Bihar   1,177   1,056   -10%    10,755    12,640      18%
10                  Sikkim     160     189    19%     1,917     2,248      17%
11       Arunachal Pradesh      85      67   -22%       398       581      46%
12                Nagaland      46      39   -16%       227       317      40%
13                 Manipur      46      36   -22%       309       435      41%
14                 Mizoram      50      33   -33%       213       296      39%
15                 Tripura      64      67     5%       556       680      22%
16               Meghalaya     127     133     5%     1,368     1,522      11%
17                   Assam     956     932    -3%     8,989    10,423      16%
18             West Bengal   3,841   3,582    -7%    39,780    43,386       9%
19               Jharkhand   2,149   2,049    -5%    23,916    22,847      -4%
20                  Odisha   2,626   2,633     0%    26,952    29,677      10%
21            Chhattisgarh   2,143   2,093    -2%    22,932    24,160       5%
22          Madhya Pradesh   2,624   2,407    -8%    25,683    28,354      10%
23                 Gujarat   6,521   6,820     5%    73,440    78,923       7%
24           Daman and Diu     103      95    -8%     1,105     1,155       5%
25  Dadra and Nagar Haveli     174     169    -3%     1,718     1,810       5%
26             Maharashtra  15,596  15,002    -4%  1,70,289  1,85,917       9%
27               Karnataka   6,983   7,144     2%    78,763    83,408       6%
28                     Goa     389     316   -19%     4,103     4,280       4%
29             Lakshadweep       1       1    54%        20        20       2%
30                  Kerala   1,635   1,475   -10%    16,343    19,234      18%
31              Tamil Nadu   6,941   6,178   -11%    70,562    74,430       5%
32              Puducherry     184     149   -19%     1,924     1,871      -3%
33                 Andaman     NaN     NaN    NaN       NaN       NaN      NaN
34                     NaN      28      39    40%       297       361      21%
35         &NicobarIslands     NaN     NaN    NaN       NaN       NaN      NaN
36               Telangana   3,897   3,563    -9%    36,408    39,820       9%
37          Andhra Pradesh   2,589   2,548    -2%    25,331    27,108       7%
38         Other Territory     167     133   -21%     2,484     1,753     -29%
39     Center Jurisdiction      74      81    10%       580     1,003      73%
40                   Total  82,165  78,700    -4%  8,76,794  9,44,414       8%